# Dependencies

In [1]:
import pandas as pd
import requests
import json
from config import api_key

In [2]:
# Data Retrieval

In [3]:
#create the url and get the json response of all the states 
url = f"http://api.eia.gov/category/?api_key={api_key}&category_id=238627"
USA_JSON = requests.get(url).json()

# Create 
child = USA_JSON['category']['childseries']

In [4]:
# Create a for loop to append the states series ID to the annual or montly list 
monthly_series_id = []
annual_series_id = []
for cuban in child:
    if cuban['f'] == 'M':
        monthly_series_id.append(cuban['series_id'])
    elif cuban['f'] == 'A':
        annual_series_id.append(cuban['series_id'])

## Annual Gas Data

In [5]:
dict_annual = {}
year = True

# Replace the url for state
for series in annual_series_id:
    url_state = f'https://api.eia.gov/series/?api_key={api_key}&series_id={series}'
    state_request = requests.get(url_state).json()
    data = state_request['series'][0]
    state = data['geography'].split('-')

    for value in data['data']:
            if value[+1] != None:
                if year == True:
                    dict_annual.setdefault('Year', []).append(value[0])
                if len(state) == 2:
                    dict_annual.setdefault(f'{state[1]}', []).append(value[1])
    year = False

In [6]:
# Remove DC as it does equal the total array number
dict_annual.pop('DC')

[2.379, 0.981, 1.075]

In [7]:
# Create Dataframe and set index
df_annual = pd.DataFrame(dict_annual)
# .set_index('Year')
df_annual.rename(columns={"Year":'Date'}, inplace = True)

df_annual

,Date,AK,AL,AR,AZ,CA,CO,CT,DE,FL,...,SD,TN,TX,UT,VA,VT,WA,WI,WV,WY
0,2010,3.095,2.233,2.231,2.324,2.503,2.213,2.387,2.286,2.254,...,2.339,2.212,2.209,2.379,2.263,2.406,2.398,2.282,2.342,2.309
1,2009,2.595,1.802,1.745,1.882,2.093,1.814,1.911,1.843,1.834,...,1.905,1.787,1.800,1.869,1.838,1.973,1.983,1.874,1.917,1.838
2,2008,3.383,2.754,2.693,2.765,2.891,2.742,2.779,2.728,2.741,...,2.736,2.719,2.695,2.752,2.735,2.917,2.833,2.725,2.815,2.811
3,2007,2.528,2.254,2.293,2.332,2.457,2.376,2.356,2.250,2.269,...,2.391,2.247,2.263,2.291,2.265,2.406,2.389,2.354,2.326,2.409
4,2006,2.385,2.056,2.022,2.172,2.257,2.122,2.176,2.128,2.079,...,2.136,2.038,2.061,2.062,2.083,2.182,2.176,2.116,2.104,2.157
5,2005,2.086,1.794,1.751,1.934,1.950,1.831,1.830,1.793,1.793,...,1.818,1.774,1.760,1.777,1.792,1.880,1.872,1.814,1.819,1.875
6,2004,1.690,1.357,1.337,1.545,1.617,1.405,1.450,1.409,1.370,...,1.414,1.344,1.325,1.395,1.362,1.491,1.470,1.419,1.405,1.427
7,2003,1.460,1.042,1.048,1.286,1.303,1.122,1.150,1.098,1.072,...,1.138,1.037,1.031,1.131,1.074,1.180,1.185,1.134,1.112,1.147
8,2002,1.266,0.880,0.880,0.932,0.980,0.955,0.947,0.898,0.893,...,0.968,0.863,0.864,0.894,0.898,0.979,0.922,0.950,0.917,0.986
9,2001,1.365,0.935,0.936,1.045,1.113,1.084,1.057,0.976,0.929,...,1.088,0.921,0.913,0.982,0.961,1.029,1.065,1.044,0.970,1.071
10,2000,1.314,1.017,1.003,1.114,1.155,1.083,1.133,1.085,1.008,...,1.143,0.990,0.991,1.060,1.043,1.126,1.153,1.087,1.055,1.121
11,1999,0.978,0.684,0.664,0.813,0.875,0.763,0.746,0.712,0.692,...,0.768,0.660,0.670,0.793,0.693,0.776,0.856,0.737,0.689,0.832
12,1998,0.963,0.618,0.582,0.707,0.694,0.687,0.633,0.604,0.605,...,0.697,0.572,0.576,0.661,0.611,0.651,0.672,0.635,0.617,0.735
13,1997,1.162,0.788,0.754,0.936,0.868,0.865,0.829,0.785,0.782,...,0.862,0.751,0.754,0.864,0.786,0.855,0.869,0.800,0.799,0.907
14,1996,1.205,0.783,0.759,0.937,0.860,0.865,0.830,0.799,0.793,...,0.861,0.767,0.785,0.840,0.795,0.873,0.913,0.830,0.812,0.904
15,1995,1.137,0.720,0.683,0.802,0.743,0.776,0.759,0.740,0.712,...,0.772,0.681,0.716,0.735,0.718,0.801,0.808,0.735,0.759,0.822
16,1994,1.091,0.674,0.663,0.796,0.718,0.778,0.711,0.665,0.669,...,0.754,0.646,0.673,0.700,0.672,0.772,0.768,0.700,0.721,0.807
17,1993,1.058,0.704,0.694,0.843,0.770,0.789,0.744,0.676,0.704,...,0.792,0.672,0.697,0.731,0.698,0.789,0.760,0.704,0.747,0.821
18,1992,1.119,0.747,0.716,0.820,0.813,0.808,0.795,0.747,0.729,...,0.820,0.709,0.736,0.773,0.734,0.845,0.809,0.754,0.784,0.883
19,1991,1.041,0.790,0.764,0.761,0.718,0.780,0.852,0.804,0.773,...,0.842,0.741,0.792,0.758,0.760,0.926,0.774,0.796,0.820,0.858
20,1990,1.141,0.890,0.853,0.891,0.879,0.861,0.927,0.887,0.875,...,0.932,0.853,0.866,0.868,0.865,0.958,0.888,0.864,0.893,0.935
21,1989,0.964,0.776,0.713,0.758,0.763,0.742,0.795,0.724,0.735,...,0.835,0.709,0.709,0.752,0.744,0.854,0.731,0.725,0.774,0.835
22,1988,0.920,0.661,0.640,0.660,0.691,0.653,0.746,0.654,0.672,...,0.678,0.646,0.651,0.688,0.682,0.765,0.653,0.644,0.701,0.709
23,1987,0.925,0.681,0.664,0.714,0.677,0.700,0.718,0.654,0.679,...,0.700,0.652,0.651,0.670,0.668,0.756,0.651,0.672,0.697,0.717
24,1986,0.977,0.665,0.616,0.693,0.668,0.641,0.689,0.628,0.627,...,0.666,0.637,0.608,0.634,0.649,0.751,0.665,0.628,0.685,0.691
25,1985,1.035,0.954,0.926,0.954,0.924,0.965,0.945,0.927,0.936,...,0.994,0.923,0.910,0.913,0.937,0.993,0.931,0.941,0.965,0.971
26,1984,0.967,0.938,0.927,0.959,0.953,0.917,0.933,0.908,0.931,...,1.012,0.930,0.926,0.917,0.931,0.991,0.935,0.943,0.965,0.998

In [8]:
# Export to a CSV
df_annual.to_json("../Output/States_Annually.json", orient="records")

## Month Gas Data

In [9]:
dict_monthly = {}
year = True
for series in monthly_series_id:
    url_state = f'https://api.eia.gov/series/?api_key={api_key}&series_id={series}'
    state_request = requests.get(url_state).json()
    data = state_request['series'][0]
    state = data['geography'].split('-')
    for value in data['data']:
        x= list(value[0])
        date = f'{x[0]}{x[1]}{x[2]}{x[3]}-{x[4]}{x[5]}'
        if value[1] != None:
            if year == True:
                dict_monthly.setdefault('Year', []).append(date)
            if len(state) == 2:
                dict_monthly.setdefault(f'{state[1]}', []).append(value[1])
    year = False

In [10]:
df_monthly = pd.DataFrame(dict([(k,pd.Series(v)) for k,v in dict_monthly.items() ])).drop('DC', axis = 1)
df_monthly

,Year,AK,AL,AR,AZ,CA,CO,CT,DE,FL,...,SD,TN,TX,UT,VA,VT,WA,WI,WV,WY
0,2011-02,3.287,2.659,2.707,2.774,2.911,2.555,2.815,2.691,2.663,...,2.759,2.620,2.634,2.591,2.663,2.846,2.691,2.687,2.751,2.533
1,2011-01,3.190,2.556,2.562,2.562,2.746,2.423,2.738,2.671,2.599,...,2.646,2.527,2.510,2.319,2.596,2.771,2.586,2.594,2.671,2.412
2,2010-12,3.167,2.450,2.464,2.446,2.664,2.260,2.663,2.577,2.486,...,2.533,2.420,2.403,2.307,2.499,2.694,2.515,2.487,2.567,2.349
3,2010-11,3.129,2.296,2.287,2.347,2.560,2.212,2.540,2.431,2.325,...,2.435,2.268,2.246,2.321,2.337,2.535,2.445,2.364,2.448,2.320
4,2010-10,3.112,2.242,2.239,2.276,2.509,2.220,2.412,2.319,2.261,...,2.379,2.220,2.219,2.352,2.275,2.413,2.403,2.314,2.367,2.337
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
333,1983-05,NaN,0.991,1.023,0.950,1.012,0.951,1.001,1.006,0.991,...,1.002,1.006,0.979,0.937,1.002,1.006,0.854,0.993,1.018,1.019
334,1983-04,NaN,0.958,NaN,0.903,0.941,0.917,0.941,0.977,0.964,...,0.959,1.001,0.930,0.892,0.958,NaN,0.806,1.005,1.003,0.999
335,1983-03,NaN,0.931,NaN,0.961,0.877,0.935,0.975,0.943,0.942,...,0.931,0.929,0.917,0.855,0.926,NaN,0.853,0.916,0.960,0.942
336,1983-02,NaN,0.958,NaN,1.046,0.880,0.987,1.072,0.984,0.980,...,0.944,0.958,0.954,0.900,0.948,NaN,0.942,0.961,1.005,1.052
337,1983-01,NaN,0.995,NaN,NaN,0.955,NaN,1.115,1.024,1.012,...,1.005,1.019,0.995,1.043,0.987,NaN,NaN,0.993,1.047,1.140

In [11]:
df_monthly.rename(columns={"Year":'Date'}, inplace = True)
df_monthly

,Date,AK,AL,AR,AZ,CA,CO,CT,DE,FL,...,SD,TN,TX,UT,VA,VT,WA,WI,WV,WY
0,2011-02,3.287,2.659,2.707,2.774,2.911,2.555,2.815,2.691,2.663,...,2.759,2.620,2.634,2.591,2.663,2.846,2.691,2.687,2.751,2.533
1,2011-01,3.190,2.556,2.562,2.562,2.746,2.423,2.738,2.671,2.599,...,2.646,2.527,2.510,2.319,2.596,2.771,2.586,2.594,2.671,2.412
2,2010-12,3.167,2.450,2.464,2.446,2.664,2.260,2.663,2.577,2.486,...,2.533,2.420,2.403,2.307,2.499,2.694,2.515,2.487,2.567,2.349
3,2010-11,3.129,2.296,2.287,2.347,2.560,2.212,2.540,2.431,2.325,...,2.435,2.268,2.246,2.321,2.337,2.535,2.445,2.364,2.448,2.320
4,2010-10,3.112,2.242,2.239,2.276,2.509,2.220,2.412,2.319,2.261,...,2.379,2.220,2.219,2.352,2.275,2.413,2.403,2.314,2.367,2.337
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
333,1983-05,NaN,0.991,1.023,0.950,1.012,0.951,1.001,1.006,0.991,...,1.002,1.006,0.979,0.937,1.002,1.006,0.854,0.993,1.018,1.019
334,1983-04,NaN,0.958,NaN,0.903,0.941,0.917,0.941,0.977,0.964,...,0.959,1.001,0.930,0.892,0.958,NaN,0.806,1.005,1.003,0.999
335,1983-03,NaN,0.931,NaN,0.961,0.877,0.935,0.975,0.943,0.942,...,0.931,0.929,0.917,0.855,0.926,NaN,0.853,0.916,0.960,0.942
336,1983-02,NaN,0.958,NaN,1.046,0.880,0.987,1.072,0.984,0.980,...,0.944,0.958,0.954,0.900,0.948,NaN,0.942,0.961,1.005,1.052
337,1983-01,NaN,0.995,NaN,NaN,0.955,NaN,1.115,1.024,1.012,...,1.005,1.019,0.995,1.043,0.987,NaN,NaN,0.993,1.047,1.140

In [12]:
# Export to a CSV 
df_monthly.to_json("../Output/States_Monthly.json", orient="records")